apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJnaGNyLmlvIjogewogICAgICAgICAgICAiYXV0aCI6ICJkMlZpWjJGMGMySjVPbWRvY0Y5MVRWTnBVSGhTWW05d1NYTnBVV3cwUjBJMVptNDRjbGhKYkdoVlZrc3hOWFJhYUdnPSIKICAgICAgICB9CiAgICB9Cn0=
type: kubernetes.io/dockerconfigjson


